apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  rules:
    - host: inventory.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: inventory
                port:
                  number: 80
